name = "hlpflforms"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "hlpflforms"
database_id = "placeholder"

[vars]
JWT_SECRET = "your-secret-key-change-in-production"